# Generated by Django 4.1.2 on 2022-11-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(related_name='category_products', to='main.productcategory'),
        ),
    ]
