# Generated by Django 4.1.2 on 2022-11-07 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_products_featured_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='featured-images')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='featured_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.featuredimage'),
        ),
    ]
