# Generated by Django 4.1.2 on 2022-10-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productcategory_image_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
