# Generated by Django 4.1.2 on 2022-11-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_products_options_products_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(null=True, related_name='category_products', to='main.productcategory'),
        ),
    ]
