# Generated by Django 4.1.2 on 2022-11-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_products_category_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(related_name='category_products', to='main.productcategory'),
        ),
    ]
