# Generated by Django 4.1.2 on 2022-11-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_featuredimage_alter_products_featured_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='featured_images',
        ),
        migrations.AddField(
            model_name='products',
            name='featured_image1',
            field=models.ImageField(blank=True, null=True, upload_to='featured-images'),
        ),
        migrations.AddField(
            model_name='products',
            name='featured_image2',
            field=models.ImageField(blank=True, null=True, upload_to='featured-images'),
        ),
        migrations.AddField(
            model_name='products',
            name='featured_image3',
            field=models.ImageField(blank=True, null=True, upload_to='featured-images'),
        ),
        migrations.AddField(
            model_name='products',
            name='featured_image4',
            field=models.ImageField(blank=True, null=True, upload_to='featured-images'),
        ),
        migrations.DeleteModel(
            name='FeaturedImage',
        ),
    ]
