# Generated by Django 4.1.2 on 2022-12-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_customer_user_remove_vendor_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '4: Customers'},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name_plural': '7: Customer Addresses'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '5: Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name_plural': '6: Order Items'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': '2: Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productrating',
            options={'verbose_name_plural': '8: Product Ratings'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': '3: Products'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': '1: Vendors'},
        ),
        migrations.AlterField(
            model_name='products',
            name='featured_image3',
            field=models.ImageField(null=True, upload_to='featured-images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='featured_image4',
            field=models.ImageField(null=True, upload_to='featured-images'),
        ),
    ]
