# Generated by Django 4.1.2 on 2022-12-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_customer_options_alter_customeraddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='featured_image1',
            field=models.ImageField(null=True, upload_to='featured-images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='featured_image2',
            field=models.ImageField(null=True, upload_to='featured-images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='featured_image3',
            field=models.ImageField(blank=True, null=True, upload_to='featured-images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='featured_image4',
            field=models.ImageField(blank=True, null=True, upload_to='featured-images'),
        ),
    ]
