# Generated by Django 4.1.2 on 2022-12-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_products_featured_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='detail',
            field=models.TextField(default='detail'),
        ),
    ]
