# Generated by Django 4.1.2 on 2022-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_products_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='detail',
            field=models.TextField(default='detail', null=True),
        ),
    ]
