# Generated by Django 4.1.2 on 2022-12-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_products_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='featured_image1',
        ),
        migrations.AddField(
            model_name='products',
            name='afeatured_image1',
            field=models.ImageField(blank=True, null=True, upload_to='featured-images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='featured_image2',
            field=models.ImageField(blank=True, null=True, upload_to='featured-images'),
        ),
    ]
