# Generated by Django 4.1.2 on 2022-12-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_products_featured_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='afeatured_image1',
            new_name='featured_image1',
        ),
    ]
