# Generated by Django 4.1.2 on 2022-12-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_products_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
