# Generated by Django 4.1.2 on 2022-12-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_products_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
