# Generated by Django 4.1.2 on 2023-01-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_products_category_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='detail',
            field=models.TextField(default='detail'),
        ),
        migrations.AlterField(
            model_name='products',
            name='tags',
            field=models.TextField(default='tags'),
        ),
    ]
