# Generated by Django 4.1.5 on 2023-03-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
