# Generated by Django 4.1.5 on 2023-03-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_vendor_is_active_vendor_is_staff_vendor_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
